AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Documentation: # Do not require documentation from tests
  Exclude:
    - 'spec/**/*.rb'
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*.rb'
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 30
  CountComments: false
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
Style/MutableConstant:
  Enabled: false
Style/GuardClause:
  Enabled: false
